# Generated by Django 5.2.6 on 2026-08-15 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('canceled', 'Cancelado')], default='active', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('recruitment_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitmentprocess')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('candidate', 'recruitment_process'), name='unique_active_application_per_candidate_process')],
            },
        ),
    ]
