# Generated by Django 5.2.6 on 2026-08-15 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_active_application_per_candidate_process',
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'recruitment_process'), name='unique_active_application_per_candidate_process'),
        ),
    ]
