# Generated by Django 5.2.6 on 2026-08-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_application_unique_active_application_per_candidate_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_review', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Reprovado')], default='in_review', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progresses', to='recruitment.application')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_progresses', to='recruitment.stage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'stage'), name='unique_stage_progress_per_application_stage')],
            },
        ),
    ]
