# Generated by Django 5.2.6 on 2026-08-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_stageprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprocess',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
