# Generated by Django 5.2.6 on 2026-08-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_recruitmentprocess_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('canceled', 'Cancelado'), ('approved', 'aprovado'), ('rejected', 'Reprovado')], default='active', max_length=20),
        ),
    ]
